language: ruby

rvm:
  - 2.7.3

install:
  - bundle install --jobs 3 --retry 3
  - nvm install 10
  - node -v
  - npm i -g yarn
  - yarn

env:
  global:
    - MOZ_HEADLESS=1

addons:
  firefox: latest

script:
  - rake db:migrate RAILS_ENV=test
  - rake db:seed RAILS_ENV=test
  - rails webpacker:compile

  - rails test test/models/product_test.rb
  - rails test test/models/sale_test.rb
  - rails test test/models/user_test.rb
  - rails test test/models/address_test.rb
  - rails test test/models/post_test.rb
  - rails test test/models/product_test.rb
  
  - cucumber features/product.feature
  - cucumber features/sale.feature
  - cucumber features/user.feature
  - cucumber features/acesso.feature
  - cucumber features/entregador.feature
  - cucumber features/entrega.feature